/**
 * Claude provider adapter - real implementation, activated only when a
 * secure server-side gateway is actually deployed and configured.
 *
 * SECURITY BOUNDARY (do not change without a real security review):
 * This class contains no API key and makes no direct call to Anthropic's
 * API. It only ever calls AI_GATEWAY_URL (a non-secret Cloudflare Worker
 * endpoint - see cloudflare/ai-gateway/) which holds ANTHROPIC_API_KEY as a
 * server-side secret. Every request carries the current ASFOUR user's real
 * Firebase ID token so the gateway can verify it before spending API
 * quota - this class never invents or reuses another user's identity.
 *
 * This class NEVER touches Firestore, ERP services, or arbitrary JS
 * execution - exactly like MockProvider, it only ever returns a
 * ToolCallRequest (a tool name + arguments) that the Gateway resolves
 * against the Tool Registry, permission-checks, validates, and executes.
 * Claude itself never sees a Firestore handle or an ERP service function -
 * only tool NAMES, DESCRIPTIONS, and JSON SCHEMAS (see ToolSummary).
 */
import { CLAUDE_MODEL } from '../config';
import {
  AIProvider,
  AIProviderTurn,
  AssistantMessage,
  CommandType,
  ScreenContext,
  ToolExecutionResult,
  ToolResultAnalysis,
  ToolSummary,
} from '../types';
import { buildSystemPrompt, historyToMessages, buildInferencePrompt } from './promptBuilder';
import { callGatewayChat, isGatewayConfigured } from './gatewayClient';

// Mirrors providerRegistry.ts's displayNameEn for 'claude' - kept as a
// local literal (not imported from the registry) to avoid a circular
// import, since providerRegistry.ts itself imports this class.
const PROVIDER_DISPLAY_NAME = 'Claude (Anthropic)';

export class ClaudeProvider implements AIProvider {
  readonly providerId = 'claude' as const;

  get isConfigured(): boolean {
    // Only ever true once a real secure gateway URL is configured. Never
    // true just because AI_PROVIDER="claude" was set - that would let the
    // app silently claim Claude is active with nothing behind it.
    return isGatewayConfigured();
  }

  private notConfiguredError(): never {
    throw new Error(
      'ClaudeProvider is not configured. Set VITE_AI_GATEWAY_URL to a deployed ' +
      `secure AI gateway (see cloudflare/ai-gateway/README.md). Model hint: ${CLAUDE_MODEL || 'unset'}.`
    );
  }

  async generateWithTools(
    userText: string,
    context: ScreenContext,
    availableTools: ToolSummary[],
    history: AssistantMessage[]
  ): Promise<AIProviderTurn> {
    if (!this.isConfigured) this.notConfiguredError();

    const tools = availableTools
      .filter((t) => t.parameterSchema)
      .map((t) => ({
        name: t.toolName,
        description: context.currentLanguage === 'ar' ? t.descriptionAr : t.descriptionEn,
        input_schema: t.parameterSchema as Record<string, any>,
      }));

    const messages = [...historyToMessages(history), { role: 'user' as const, content: userText }];
    const response = await callGatewayChat({ provider: 'claude', system: buildSystemPrompt(context, PROVIDER_DISPLAY_NAME), messages, tools });

    if (response.type === 'tool_use' && response.toolName) {
      const matchedTool = availableTools.find((t) => t.toolName === response.toolName);
      const commandType: CommandType = matchedTool?.commandType || 'UNKNOWN';
      return { commandType, toolCall: { toolName: response.toolName, arguments: response.arguments || {} } };
    }

    return { commandType: 'UNKNOWN', responseText: response.text || '' };
  }

  async analyzeToolResult(toolName: string, result: ToolExecutionResult, context: ScreenContext): Promise<ToolResultAnalysis> {
    if (!this.isConfigured) this.notConfiguredError();

    // The factual summary always comes directly from the tool's own
    // bilingual message - never regenerated by the model, so it can never
    // drift from what the tool actually computed. Claude is only asked for
    // the OPTIONAL interpretive add-on, clearly separated from fact.
    const factualSummaryAr = result.messageAr || 'تم تنفيذ العملية.';
    const factualSummaryEn = result.messageEn || 'Operation completed.';

    if (!result.success) {
      return { factualSummaryAr, factualSummaryEn };
    }

    try {
      const response = await callGatewayChat({
        provider: 'claude',
        system: buildSystemPrompt(context, PROVIDER_DISPLAY_NAME),
        messages: [{ role: 'user', content: buildInferencePrompt(toolName, result.data) }],
      });
      const parsed = JSON.parse((response.text || '').trim());
      if (parsed && typeof parsed.inferenceAr === 'string' && typeof parsed.inferenceEn === 'string') {
        return { factualSummaryAr, factualSummaryEn, inferenceAr: parsed.inferenceAr, inferenceEn: parsed.inferenceEn };
      }
    } catch {
      // A failed/unparsable inference call must never break the factual
      // response the user already has - fall through to facts-only.
    }
    return { factualSummaryAr, factualSummaryEn };
  }

  async generateResponse(userText: string, context: ScreenContext, history: AssistantMessage[]): Promise<string> {
    if (!this.isConfigured) this.notConfiguredError();

    const messages = [...historyToMessages(history), { role: 'user' as const, content: userText }];
    const response = await callGatewayChat({ provider: 'claude', system: buildSystemPrompt(context, PROVIDER_DISPLAY_NAME), messages });
    return response.text || (context.currentLanguage === 'ar' ? 'تعذر تنفيذ العملية.' : 'Unable to complete the operation.');
  }

  async streamResponse(userText: string, context: ScreenContext, onChunk: (chunk: string) => void): Promise<void> {
    // Phase 1: no real SSE streaming through the Worker yet - a single
    // complete response is delivered as one chunk rather than faking a
    // stream. See cloudflare/ai-gateway/README.md "Known limitations".
    const text = await this.generateResponse(userText, context, []);
    onChunk(text);
  }
}
