/**
 * Logical item identity - Phase 1 Step 2A. Pure and Firebase-free.
 *
 * THE PROBLEM. One physical item (calcined kaolin, crushed brick...) can exist
 * as a `products` record AND a `materials` record. Step 1B finds such pairs
 * deterministically (itemOverlapAnalysisPure.ts) but recorded nothing.
 *
 * THE LAYER. A logical item is a small identity document in `logicalItems`:
 * its document id IS the logicalItemId (generated by Firestore - never a
 * product id, material id, code or external id), plus references to at most
 * one product and at most one material. Both source records stay exactly as
 * they are: nothing here reads, copies or writes a code, name, category, cost,
 * stock or mixture. Neither side is the "winner"; `preferredSource` exists for
 * an explicit future choice and is null unless someone sets it.
 *
 * ONLY EXPLICIT DECISIONS. Nothing is mapped automatically - not exact
 * code+name matches, not name matches, nothing fuzzy. A logical item is created
 * only when a user confirms "Map as Same Logical Item" for one product/material
 * pair. "Keep Separate" is a separate, equally explicit decision, stored in
 * `itemPairDecisions`, so "reviewed and kept apart" is never confused with "not
 * reviewed yet".
 *
 * UNIQUENESS. Among ACTIVE logical items a product appears at most once and a
 * material appears at most once, so a pair can never be mapped twice. Every
 * outcome is planned from the stored state before anything is written, and each
 * decision writes exactly one document - a refused plan writes nothing.
 *
 * NOTHING IS DELETED. A mapping or decision that is withdrawn becomes INACTIVE
 * and stays readable.
 *
 * SINGLE-RECORD REGISTRATION (Phase 1 Step 3). A plain product (a brick) or
 * material with no twin can be registered as a logical item on its own - again
 * only by an explicit, confirmed action. It is refused while that record still
 * has an UNDECIDED overlap row (candidate, needs review, ambiguous or conflict):
 * every such pair must first be mapped or kept separate, so registering one side
 * can never split a real product/material pair into two identities. A later
 * mapping with its twin attaches to the registered item instead of creating a
 * second one.
 *
 * WHO USES IT. `resolveLogicalItemId` turns a (collection, id) record reference
 * into its logical item, so a BOM line, and later costing, treats a mapped
 * product and material as the same item without storing a second identity.
 */

export const LOGICAL_ITEM_COLLECTION = 'logicalItems';
export const ITEM_PAIR_DECISION_COLLECTION = 'itemPairDecisions';

export const LOGICAL_ITEM_STATUSES = ['ACTIVE', 'INACTIVE'] as const;
export type LogicalItemStatusValue = (typeof LOGICAL_ITEM_STATUSES)[number];

export type LogicalItemSource = 'products' | 'materials';

export interface LogicalItemRecord {
  id: string;
  productId: string | null;
  materialId: string | null;
  preferredSource: LogicalItemSource | null;
  status: LogicalItemStatusValue;
  reason: string;
}

export interface ItemPairDecisionRecord {
  id: string;
  productId: string;
  materialId: string;
  decision: 'KEEP_SEPARATE';
  status: LogicalItemStatusValue;
  reason: string;
}

export interface ProductMaterialPair {
  productId: string;
  materialId: string;
}

function text(value: unknown): string {
  return typeof value === 'string' ? value.trim() : value == null ? '' : String(value).trim();
}

function optionalId(value: unknown): string | null {
  const t = text(value);
  return t === '' ? null : t;
}

function statusOf(value: unknown): LogicalItemStatusValue {
  return text(value).toUpperCase() === 'INACTIVE' ? 'INACTIVE' : 'ACTIVE';
}

/** Tolerant read of a stored logical item. */
export function readLogicalItem(raw: Record<string, unknown> & { id?: string }): LogicalItemRecord {
  const preferred = text(raw.preferredSource);
  return {
    id: text(raw.id),
    productId: optionalId(raw.productId),
    materialId: optionalId(raw.materialId),
    preferredSource: preferred === 'products' || preferred === 'materials' ? preferred : null,
    status: statusOf(raw.status),
    reason: text(raw.reason),
  };
}

/** Tolerant read of a stored pair decision. */
export function readItemPairDecision(raw: Record<string, unknown> & { id?: string }): ItemPairDecisionRecord {
  return {
    id: text(raw.id),
    productId: text(raw.productId),
    materialId: text(raw.materialId),
    decision: 'KEEP_SEPARATE',
    status: statusOf(raw.status),
    reason: text(raw.reason),
  };
}

const active = <T extends { status: LogicalItemStatusValue }>(list: readonly T[]) => list.filter((x) => x.status === 'ACTIVE');

/** The ACTIVE logical item that contains this record, if any. */
export function findLogicalItemFor(items: readonly LogicalItemRecord[], source: LogicalItemSource, recordId: string): LogicalItemRecord | undefined {
  const id = text(recordId);
  if (!id) return undefined;
  return active(items).find((i) => (source === 'products' ? i.productId === id : i.materialId === id));
}

/**
 * The logical identity of a record reference: its ACTIVE logical item id when
 * it has one, otherwise a stable key for the record itself. Two references
 * with the same result are the same logical item.
 */
export function resolveLogicalItemId(items: readonly LogicalItemRecord[], source: string, recordId: string): string {
  const s = text(source);
  const id = text(recordId);
  if ((s === 'products' || s === 'materials') && id) {
    const item = findLogicalItemFor(items, s, id);
    if (item) return `logicalItem:${item.id}`;
  }
  return `record:${s}/${id}`;
}

/** The source records of a logical item - what future costing reads cost data from. */
export function logicalItemSources(item: LogicalItemRecord): Array<{ source: LogicalItemSource; recordId: string }> {
  return [
    ...(item.productId ? [{ source: 'products' as const, recordId: item.productId }] : []),
    ...(item.materialId ? [{ source: 'materials' as const, recordId: item.materialId }] : []),
  ];
}

// --- Planning -----------------------------------------------------------------------

export type MappingConflictKind = 'PRODUCT_MAPPED_ELSEWHERE' | 'MATERIAL_MAPPED_ELSEWHERE' | 'SPLIT_IDENTITIES' | 'KEPT_SEPARATE' | 'INVALID_PAIR';

export interface MappingConflict {
  kind: MappingConflictKind;
  logicalItemId?: string;
  decisionId?: string;
}

export type MappingOutcome = 'CREATE' | 'ATTACH_MATERIAL' | 'ATTACH_PRODUCT' | 'ALREADY_MAPPED' | 'CONFLICT';

export interface MappingPlan {
  outcome: MappingOutcome;
  /** The logical item written or found (ATTACH_* / ALREADY_MAPPED), or involved in a conflict. */
  logicalItemId?: string;
  conflicts: MappingConflict[];
  messageAr: string;
  messageEn: string;
}

function conflictMessages(conflicts: MappingConflict[]): { ar: string; en: string } {
  const ar: string[] = [];
  const en: string[] = [];
  for (const c of conflicts) {
    if (c.kind === 'PRODUCT_MAPPED_ELSEWHERE') {
      ar.push(`المنتج مرتبط بالفعل بصنف منطقي آخر (${c.logicalItemId}).`);
      en.push(`The product is already mapped to another logical item (${c.logicalItemId}).`);
    } else if (c.kind === 'MATERIAL_MAPPED_ELSEWHERE') {
      ar.push(`الخامة مرتبطة بالفعل بصنف منطقي آخر (${c.logicalItemId}).`);
      en.push(`The material is already mapped to another logical item (${c.logicalItemId}).`);
    } else if (c.kind === 'SPLIT_IDENTITIES') {
      ar.push(`المنتج والخامة لكل منهما صنف منطقي مختلف (${c.logicalItemId}) - لا يتم دمج الهويات.`);
      en.push(`The product and the material each have a different logical item (${c.logicalItemId}) - identities are never merged.`);
    } else if (c.kind === 'KEPT_SEPARATE') {
      ar.push(`تم تسجيل قرار «إبقاء منفصل» لهذا الزوج (${c.decisionId}). ألغِ القرار أولًا.`);
      en.push(`This pair was explicitly kept separate (${c.decisionId}). Withdraw that decision first.`);
    } else {
      ar.push('يجب تحديد منتج وخامة.');
      en.push('A product and a material are both required.');
    }
  }
  return { ar: ar.join(' '), en: en.join(' ') };
}

/**
 * Plans "Map as Same Logical Item" for one product/material pair. Writes nothing.
 *
 *   ALREADY_MAPPED   one ACTIVE item already holds exactly this pair - idempotent, no write
 *   ATTACH_MATERIAL  the product has an ACTIVE item with no material; the material is free
 *   ATTACH_PRODUCT   the material has an ACTIVE item with no product; the product is free
 *   CREATE           neither record is in an ACTIVE item
 *   CONFLICT         either record belongs to an item holding something else, each belongs
 *                    to a different item, or the pair was explicitly kept separate
 */
export function planProductMaterialMapping(
  items: readonly LogicalItemRecord[],
  decisions: readonly ItemPairDecisionRecord[],
  pair: ProductMaterialPair,
): MappingPlan {
  const productId = text(pair.productId);
  const materialId = text(pair.materialId);
  const refuse = (conflicts: MappingConflict[], logicalItemId?: string): MappingPlan => {
    const m = conflictMessages(conflicts);
    return { outcome: 'CONFLICT', logicalItemId, conflicts, messageAr: m.ar, messageEn: m.en };
  };
  if (!productId || !materialId) return refuse([{ kind: 'INVALID_PAIR' }]);

  const byProduct = findLogicalItemFor(items, 'products', productId);
  const byMaterial = findLogicalItemFor(items, 'materials', materialId);

  if (byProduct && byMaterial && byProduct.id === byMaterial.id) {
    return { outcome: 'ALREADY_MAPPED', logicalItemId: byProduct.id, conflicts: [], messageAr: 'المنتج والخامة مرتبطان بالفعل كصنف منطقي واحد.', messageEn: 'The product and material are already mapped as one logical item.' };
  }

  const conflicts: MappingConflict[] = [];
  const keptSeparate = active(decisions).find((d) => d.productId === productId && d.materialId === materialId);
  if (keptSeparate) conflicts.push({ kind: 'KEPT_SEPARATE', decisionId: keptSeparate.id });
  if (byProduct && byMaterial) {
    conflicts.push({ kind: 'SPLIT_IDENTITIES', logicalItemId: `${byProduct.id} / ${byMaterial.id}` });
  } else {
    if (byProduct && byProduct.materialId) conflicts.push({ kind: 'PRODUCT_MAPPED_ELSEWHERE', logicalItemId: byProduct.id });
    if (byMaterial && byMaterial.productId) conflicts.push({ kind: 'MATERIAL_MAPPED_ELSEWHERE', logicalItemId: byMaterial.id });
  }
  if (conflicts.length > 0) return refuse(conflicts, byProduct?.id ?? byMaterial?.id);

  if (byProduct) {
    return { outcome: 'ATTACH_MATERIAL', logicalItemId: byProduct.id, conflicts: [], messageAr: 'ستُضاف الخامة إلى الصنف المنطقي الموجود للمنتج.', messageEn: "The material will be added to the product's existing logical item." };
  }
  if (byMaterial) {
    return { outcome: 'ATTACH_PRODUCT', logicalItemId: byMaterial.id, conflicts: [], messageAr: 'سيُضاف المنتج إلى الصنف المنطقي الموجود للخامة.', messageEn: "The product will be added to the material's existing logical item." };
  }
  return { outcome: 'CREATE', conflicts: [], messageAr: 'سيُنشأ صنف منطقي جديد يربط المنتج والخامة.', messageEn: 'A new logical item will link the product and the material.' };
}

export type KeepSeparateOutcome = 'CREATE' | 'ALREADY_KEPT_SEPARATE' | 'CONFLICT';

/** Plans "Keep Separate" for one pair. Refused while the pair is actively mapped together. */
export function planKeepSeparate(
  items: readonly LogicalItemRecord[],
  decisions: readonly ItemPairDecisionRecord[],
  pair: ProductMaterialPair,
): { outcome: KeepSeparateOutcome; decisionId?: string; logicalItemId?: string; messageAr: string; messageEn: string } {
  const productId = text(pair.productId);
  const materialId = text(pair.materialId);
  if (!productId || !materialId) return { outcome: 'CONFLICT', messageAr: 'يجب تحديد منتج وخامة.', messageEn: 'A product and a material are both required.' };
  const existing = active(decisions).find((d) => d.productId === productId && d.materialId === materialId);
  if (existing) return { outcome: 'ALREADY_KEPT_SEPARATE', decisionId: existing.id, messageAr: 'تم تسجيل «إبقاء منفصل» لهذا الزوج بالفعل.', messageEn: 'This pair is already kept separate.' };
  const mapped = findLogicalItemFor(items, 'products', productId);
  if (mapped && mapped.materialId === materialId) {
    return { outcome: 'CONFLICT', logicalItemId: mapped.id, messageAr: `المنتج والخامة مرتبطان كصنف منطقي واحد (${mapped.id}). ألغِ الربط أولًا.`, messageEn: `The product and material are mapped as one logical item (${mapped.id}). Unlink them first.` };
  }
  return { outcome: 'CREATE', messageAr: 'سيُسجَّل قرار إبقاء المنتج والخامة منفصلين.', messageEn: 'The decision to keep the product and material separate will be recorded.' };
}

// --- Single-record registration ------------------------------------------------------------

export type RegistrationOutcome = 'CREATE' | 'ALREADY_REGISTERED' | 'CONFLICT';

export interface RegistrationPlan {
  outcome: RegistrationOutcome;
  logicalItemId?: string;
  /** Overlap pairs involving the record that are neither mapped nor kept separate. */
  undecidedPairs: ProductMaterialPair[];
  messageAr: string;
  messageEn: string;
}

/**
 * Plans "Register as Logical Item" for one product or material. Writes nothing.
 * `overlapRows` are the analyzer's current rows (itemOverlapAnalysisPure) - the
 * matching is never redone here.
 */
export function planSingleRecordRegistration(
  items: readonly LogicalItemRecord[],
  decisions: readonly ItemPairDecisionRecord[],
  source: LogicalItemSource,
  recordId: string,
  overlapRows: ReadonlyArray<{ materialId: string; productId?: string }>,
): RegistrationPlan {
  const id = text(recordId);
  if (!id || (source !== 'products' && source !== 'materials')) {
    return { outcome: 'CONFLICT', undecidedPairs: [], messageAr: 'يجب تحديد منتج أو خامة.', messageEn: 'A product or a material is required.' };
  }
  const existing = findLogicalItemFor(items, source, id);
  if (existing) {
    return { outcome: 'ALREADY_REGISTERED', logicalItemId: existing.id, undecidedPairs: [], messageAr: `السجل له صنف منطقي بالفعل (${existing.id}).`, messageEn: `The record already has a logical item (${existing.id}).` };
  }
  const involving = overlapRows.filter((r) => r.productId && (source === 'materials' ? r.materialId === id : r.productId === id));
  const undecidedPairs = involving
    .filter((r) => !active(decisions).some((d) => d.productId === r.productId && d.materialId === r.materialId))
    .map((r) => ({ productId: String(r.productId), materialId: r.materialId }));
  if (undecidedPairs.length > 0) {
    return {
      outcome: 'CONFLICT',
      undecidedPairs,
      messageAr: `لهذا السجل ${undecidedPairs.length} تطابق لم يُحسم بعد مع ${source === 'materials' ? 'منتجات' : 'خامات'}. اربطه أو اختر «إبقاء منفصل» لكل تطابق أولًا.`,
      messageEn: `This record has ${undecidedPairs.length} undecided overlap(s) with ${source === 'materials' ? 'products' : 'materials'}. Map or keep separate each one first.`,
    };
  }
  return { outcome: 'CREATE', undecidedPairs: [], messageAr: 'سيُنشأ صنف منطقي لهذا السجل وحده.', messageEn: 'A logical item will be created for this record alone.' };
}

// --- Payloads -------------------------------------------------------------------------

export interface DecisionMeta {
  /** The row's match type or a short note - why the user decided. */
  reason?: string;
  userId?: string | null;
}

/** The new logical item document: references only - no code, name, cost or category is copied. */
export function logicalItemPayloadForCreate(pair: ProductMaterialPair, meta: DecisionMeta = {}) {
  return {
    productId: text(pair.productId),
    materialId: text(pair.materialId),
    preferredSource: null,
    status: 'ACTIVE' as const,
    reason: text(meta.reason),
    createdBy: optionalId(meta.userId),
    updatedBy: optionalId(meta.userId),
  };
}

/** A logical item for one record only - the other reference stays empty until a later explicit mapping attaches it. */
export function logicalItemRegistrationPayload(source: LogicalItemSource, recordId: string, meta: DecisionMeta = {}) {
  return {
    productId: source === 'products' ? text(recordId) : null,
    materialId: source === 'materials' ? text(recordId) : null,
    preferredSource: null,
    status: 'ACTIVE' as const,
    reason: text(meta.reason) || 'SINGLE_RECORD_REGISTRATION',
    createdBy: optionalId(meta.userId),
    updatedBy: optionalId(meta.userId),
  };
}

export function itemPairDecisionPayloadForCreate(pair: ProductMaterialPair, meta: DecisionMeta = {}) {
  return {
    productId: text(pair.productId),
    materialId: text(pair.materialId),
    decision: 'KEEP_SEPARATE' as const,
    status: 'ACTIVE' as const,
    reason: text(meta.reason),
    createdBy: optionalId(meta.userId),
    updatedBy: optionalId(meta.userId),
  };
}

// --- Review state ----------------------------------------------------------------------------

export type OverlapRowState = 'MAPPED' | 'KEPT_SEPARATE' | 'CONFLICT' | 'CANDIDATE' | 'NOT_REVIEWED' | 'NO_MATCH';

/**
 * What the review dialog shows for one analyzer row. The analyzer still decides
 * the match and its reason; this only adds what has been decided since.
 */
export function overlapRowState(
  row: { productId?: string; materialId: string; recommendedAction?: string },
  items: readonly LogicalItemRecord[],
  decisions: readonly ItemPairDecisionRecord[],
): { state: OverlapRowState; logicalItemId?: string; decisionId?: string; plan?: MappingPlan } {
  if (!row.productId) return { state: 'NO_MATCH' };
  const pair = { productId: row.productId, materialId: row.materialId };
  const plan = planProductMaterialMapping(items, decisions, pair);
  if (plan.outcome === 'ALREADY_MAPPED') return { state: 'MAPPED', logicalItemId: plan.logicalItemId, plan };
  const kept = active(decisions).find((d) => d.productId === pair.productId && d.materialId === pair.materialId);
  if (kept) return { state: 'KEPT_SEPARATE', decisionId: kept.id, plan };
  if (plan.outcome === 'CONFLICT') return { state: 'CONFLICT', logicalItemId: plan.logicalItemId, plan };
  if (row.recommendedAction === 'CANDIDATE_FOR_MAPPING') return { state: 'CANDIDATE', plan };
  return { state: 'NOT_REVIEWED', plan };
}

// --- Audit descriptions --------------------------------------------------------------------------

export interface RecordLabel {
  id: string;
  code?: string;
  name?: string;
}

const label = (r: RecordLabel) => `${[r.code, r.name].filter(Boolean).join(' - ') || '(no code/name)'} [${r.id}]`;

/** "Product X was mapped to Material Y as the same Logical Item L" with before/after state. */
export function describeMapping(plan: MappingPlan, product: RecordLabel, material: RecordLabel, logicalItemId: string, previous?: LogicalItemRecord | null): string {
  const before = previous ? `previous: product ${previous.productId ?? '-'}, material ${previous.materialId ?? '-'}, ${previous.status}` : 'previous: none';
  return `[LOGICAL_ITEM_MAPPED] Product ${label(product)} was mapped to Material ${label(material)} as the same Logical Item ${logicalItemId} (${plan.outcome}); ${before}; new: product ${product.id}, material ${material.id}, ACTIVE`;
}

export function describeRegistration(source: LogicalItemSource, record: RecordLabel, logicalItemId: string): string {
  return `[LOGICAL_ITEM_REGISTERED] ${source === 'products' ? 'Product' : 'Material'} ${label(record)} was registered as Logical Item ${logicalItemId} on its own; previous: none; new: ${source === 'products' ? 'product' : 'material'} ${record.id}, ACTIVE`;
}

export function describeKeepSeparate(product: RecordLabel, material: RecordLabel, decisionId: string): string {
  return `[ITEM_KEPT_SEPARATE] Product ${label(product)} and Material ${label(material)} were explicitly kept separate (decision ${decisionId}); new state: ACTIVE`;
}

export function describeRetirement(kind: 'logicalItem' | 'decision', id: string, previous: { productId: string | null; materialId: string | null }): string {
  const tag = kind === 'logicalItem' ? '[LOGICAL_ITEM_UNLINKED]' : '[ITEM_KEEP_SEPARATE_WITHDRAWN]';
  return `${tag} ${kind === 'logicalItem' ? 'Logical Item' : 'Decision'} ${id} set INACTIVE; previous: product ${previous.productId ?? '-'}, material ${previous.materialId ?? '-'}, ACTIVE; new: INACTIVE`;
}
