/**
 * Dedicated branded Print/Report renderer (Part 7 §26-29).
 *
 * Renders as a FULL-SCREEN overlay that replaces the Dashboard Builder
 * canvas in the DOM while open (the caller conditionally stops rendering
 * its own canvas - see DashboardBuilderView) and hides the app chrome
 * (sidebar/header/footer/AI button) via the `.no-print` class now applied
 * to those components (src/index.css already had a `.no-print` rule; it
 * was simply never wired to any real element before this task - the exact
 * bug Part 7 describes). This guarantees printing NEVER outputs the web
 * app's own UI, only this page: logo, company name, report title,
 * filters, generated date/by, KPIs, charts, tables, footer.
 *
 * Charts are rendered by reusing WidgetRenderer itself (editable=false, no
 * cross-filter/drill props) - one rendering path for screen AND print, not
 * a second parallel chart engine.
 */
import React, { useMemo, useState } from 'react';
import { X, Printer, FileText } from 'lucide-react';
import { UniversalStageRecord } from '../../types';
import { useBranding } from '../../context/BrandingContext';
import { WidgetRenderer } from './WidgetRenderer';
import { DashboardLayout, GlobalDashboardFilters, TIME_RANGE_LABELS, getStageDisplayName, ALL_STAGES } from '../../services/dashboardRegistry';

interface PrintReportViewProps {
  dashboard: DashboardLayout;
  allRecords: UniversalStageRecord[];
  globalFilters: GlobalDashboardFilters;
  language: 'ar' | 'en';
  generatedByName: string;
  onClose: () => void;
}

export const PrintReportView: React.FC<PrintReportViewProps> = ({
  dashboard, allRecords, globalFilters, language, generatedByName, onClose,
}) => {
  const { companyLogoSrc } = useBranding();
  const [orientation, setOrientation] = useState<'portrait' | 'landscape'>(dashboard.printOrientation || 'portrait');
  const isRtl = language === 'ar';

  const t = {
    close: language === 'ar' ? 'إغلاق' : 'Close',
    printNow: language === 'ar' ? 'طباعة الآن' : 'Print Now',
    portrait: language === 'ar' ? 'عمودي (A4)' : 'A4 Portrait',
    landscape: language === 'ar' ? 'أفقي (A4)' : 'A4 Landscape',
    companyName: language === 'ar' ? 'شركة عصفور للتعدين والحراريات' : 'ASFOUR For Mining & Refractories',
    period: language === 'ar' ? 'الفترة' : 'Period',
    stage: language === 'ar' ? 'المرحلة' : 'Stage',
    allStages: language === 'ar' ? 'كل المراحل' : 'All Stages',
    generatedOn: language === 'ar' ? 'تاريخ الإنشاء' : 'Generated On',
    generatedBy: language === 'ar' ? 'أنشئ بواسطة' : 'Generated By',
    footerNote: language === 'ar' ? 'تقرير تم إنشاؤه تلقائيًا من نظام إدارة مصنع عصفور (ERP)' : 'Auto-generated by the ASFOUR Factory Management System (ERP)',
  };

  const generatedAt = useMemo(() => new Date().toLocaleString(language === 'ar' ? 'ar-EG' : 'en-US'), [language]);

  return (
    <div className="fixed inset-0 z-[200] bg-slate-100 overflow-y-auto" dir={isRtl ? 'rtl' : 'ltr'}>
      <style>{`
        @page { size: A4 ${orientation}; margin: 14mm; }
        @media print {
          .print-toolbar { display: none !important; }
          .print-page { box-shadow: none !important; margin: 0 !important; width: 100% !important; min-height: 0 !important; }
        }
      `}</style>

      {/* Screen-only toolbar */}
      <div className="print-toolbar no-print sticky top-0 z-10 bg-white border-b border-slate-200 px-4 py-2.5 flex items-center justify-between gap-3">
        <div className="flex items-center gap-2 text-sm font-bold text-slate-700">
          <FileText className="w-4 h-4 text-indigo-600" />
          {dashboard.name}
        </div>
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-1 bg-slate-100 p-1 rounded text-xs font-bold">
            <button type="button" onClick={() => setOrientation('portrait')} className={`px-2.5 py-1 rounded cursor-pointer ${orientation === 'portrait' ? 'bg-white text-indigo-600 shadow-xs' : 'text-slate-500'}`}>{t.portrait}</button>
            <button type="button" onClick={() => setOrientation('landscape')} className={`px-2.5 py-1 rounded cursor-pointer ${orientation === 'landscape' ? 'bg-white text-indigo-600 shadow-xs' : 'text-slate-500'}`}>{t.landscape}</button>
          </div>
          <button type="button" onClick={() => window.print()} className="flex items-center gap-1.5 px-3 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold rounded cursor-pointer"><Printer className="w-3.5 h-3.5" />{t.printNow}</button>
          <button type="button" onClick={onClose} className="p-1.5 text-slate-400 hover:text-slate-700 cursor-pointer"><X className="w-4 h-4" /></button>
        </div>
      </div>

      {/* Printable page */}
      <div className={`print-page bg-white mx-auto my-6 shadow-lg p-8 ${orientation === 'landscape' ? 'max-w-[297mm]' : 'max-w-[210mm]'}`} style={{ minHeight: orientation === 'landscape' ? '210mm' : '297mm' }}>
        {/* Branded header */}
        <div className="flex items-center justify-between border-b-2 border-slate-800 pb-4 mb-5">
          <div className="flex items-center gap-3">
            {companyLogoSrc && <img src={companyLogoSrc} alt="" className="h-12 w-auto object-contain" />}
            <div>
              <p className="text-sm font-black text-slate-900">{t.companyName}</p>
              <p className="text-[10px] text-slate-500">ASFOUR ERP</p>
            </div>
          </div>
          <div className="text-end">
            <h1 className="text-lg font-black text-slate-900">{dashboard.name}</h1>
            {dashboard.isReport && <p className="text-[10px] text-slate-500">{language === 'ar' ? 'تقرير' : 'Report'}</p>}
          </div>
        </div>

        {/* Meta / filters strip */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6 text-[10px]">
          <MetaBox label={t.period} value={language === 'ar' ? TIME_RANGE_LABELS[globalFilters.timeRangePreset].ar : TIME_RANGE_LABELS[globalFilters.timeRangePreset].en} />
          <MetaBox label={t.stage} value={globalFilters.stageType === 'all' ? t.allStages : getStageDisplayName(globalFilters.stageType, language)} />
          <MetaBox label={t.generatedOn} value={generatedAt} />
          <MetaBox label={t.generatedBy} value={generatedByName} />
        </div>

        {/* Sections */}
        <div className="space-y-6">
          {dashboard.sections.map((section) => (
            <div key={section.sectionId} className="break-inside-avoid">
              <h2 className="text-xs font-black text-slate-800 uppercase tracking-wide border-b border-slate-200 pb-1.5 mb-3">{section.title}</h2>
              <div className="grid grid-cols-2 gap-3">
                {section.widgets.map((widget) => (
                  <div key={widget.widgetId} className="break-inside-avoid" style={{ height: 220 }}>
                    <WidgetRenderer
                      config={widget}
                      allRecords={allRecords}
                      globalFilters={globalFilters}
                      language={language}
                      editable={false}
                    />
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-8 pt-3 border-t border-slate-200 flex items-center justify-between text-[9px] text-slate-400">
          <span>{t.footerNote}</span>
          <span>{t.companyName}</span>
        </div>
      </div>
    </div>
  );
};

const MetaBox: React.FC<{ label: string; value: string }> = ({ label, value }) => (
  <div className="bg-slate-50 border border-slate-200 rounded px-2.5 py-1.5">
    <p className="text-slate-400 font-bold uppercase">{label}</p>
    <p className="text-slate-800 font-bold mt-0.5 truncate">{value}</p>
  </div>
);
